---
title: "About Zoe"
description: |
  Hello! You've probably already figured it out, but my name's Zoe and I'm pretty much your *classic* environmentalist. I love nothing more than shuffling my hiking boots downn a trail -- whether that's through giant sequoias (my favorite tree) or in the eastern deserts of San Diego County (my hometown stomping grounds). But less about who I am, and more about what I plan to do!
---

## Interests
My focus lies in the intersection of environmental research and communication. I have spent a substantial amount of time working in both schemes of the environmental sector, and as many have asserted before me, have found that the two cannot fucntion at max efficiency without the other. In research positions I've found that no matter how sound the results, flaws in communication strategies failed to produce substantial next steps. In communications positions, I've experienced the collapse of marketing strategies due to a lack of understanding among creators of the scientific reasoning of said plan. It is my hope to work is a position where I can serve as a connection between researchers and communicators, in order to produce high impact results -- both in the lab and in local communities. 

---

## Experience
### 2014 - 2017: Primatology & Lab Research
My Anthropology coursework at UC Davis landed me in a psych lab at the California National Primate Research Center, where I spent three years (**2015-2017**) studying primate behavior and emotion potential. In **2016**, I was given the opportunity to study abroad at the Piro Research Station in Costa Rica. Here, I spent my days hiking after spider monkeys to observe potential group patterns based on sex.

### 2018 - 2019: NGO Insights
After graduating from UC Davis, I moved to the Bay Area, where I spent the majority of **2018** interning at the Oakland Zoo -- focused on animal well-being and conservation marketing efforts. At the end of **2018** I was hired as the Conservation Program Coordinator at SaveNature.Org, where I handled all social media and communications within this small NGO.

### 2019 - 2020: Graduate School & San Diego 350
In **2019** I began my graduate degree at the Bren School of Environmental Science & Management. With a focus on Conservation Planning and Strategic Environmental Communication, my newly acquired skill set opened up an internship opportunity at SanDiego350, where I manaaged all social media and communications for this large, volunteer powered NGO.

### 2020 - 2021: Grauer's Gorilla Conservation
My thesis work on Grauer's gorilla populations in the DRC brought my experience trajectory full circle back to primate conservation. This primate project, however, aligns to a greater degree with my general interests, as it focuses on the intersection of, and potentiaal consequences of local community wellbeing and conservation efforts in the DRC.